name: yolov5_ghost
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=1.12.0
  - torchvision>=0.13.0
  - torchaudio>=0.12.0
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - numpy>=1.21.0
  - opencv>=4.6.0
  - pillow>=8.3.0
  - pyyaml>=5.4.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - pandas>=1.3.0
  - requests>=2.26.0
  - tqdm>=4.62.0
  - tensorboard>=2.7.0
  - thop
  - psutil
  - ipython
  - notebook
  - pip
  - pip:
    - ultralytics
    - roboflow
    - clearml
    - comet-ml
    - wandb
    - gitpython
    - setuptools>=65.5.1
